[tool.poetry]
name = "cliptube"
version = "0.10.5"
description = "tool to download youtube videos from the clipboard."
authors = ["ccdale <chris.charles.allison+cliptube@gmail.com>"]
readme = "README.md"
packages = [{include = "cliptube", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.12, <3.13"
pyclip = "*"
ccalogging = "*"
fabric = "*"
pysimpleguiqt = "*"
python-daemon = "*"
pyside6 = "^6.7.2"


[tool.poetry.group.dev.dependencies]
pytest = "*"

[tool.poetry.scripts]
cliptube = "cliptube.wclipboard:doTray"
orphans = "cliptube.orphans:findOrphans"
ddirwatch = "cliptube.watchdir:daemonDirWatch"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
