[tool.poetry]
name = "cliptube"
version = "0.2.12"
description = "tool to download youtube videos from the clipboard."
authors = ["ccdale <chris.charles.allison+cliptube@gmail.com>"]
readme = "README.md"
packages = [{include = "cliptube", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pyclip = "^0.7.0"
ccalogging = "^0.4.4"
fabric = "^3.0.0"
pysimpleguiqt = "^0.35.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"

[tool.poetry.scripts]
cliptube = "cliptube.ct:main"
ytdirwatch = "cliptube.watchdir:dirWatch"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
