[tool.poetry]
name = "cliptube"
version = "0.11.1"
description = "tool to download youtube videos from the clipboard."
authors = ["ccdale <chris.charles.allison+cliptube@gmail.com>"]
readme = "README.md"
packages = [{include = "cliptube", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
ccalogging = "*"
fabric = "*"


[tool.poetry.group.dev.dependencies]
pytest = "*"

[tool.poetry.scripts]
orphans = "cliptube.orphans:findOrphans"
ddirwatch = "cliptube.watchdir:daemonDirWatch"
gcbwatch = "cliptube.wclipboard:watchGnomeClipboard"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
